project_id = "dizlzsmsfdtfubopnolf"

[auth]
auto_confirm_email = true

[functions.analyze-topics]
verify_jwt = false

[functions.calendar-api]
verify_jwt = false

[functions.cron-connectors]
verify_jwt = false

[functions.dashboard-api]
verify_jwt = false

[functions.guest-run-update]
verify_jwt = false

[functions.data-status]
verify_jwt = false

[functions.digest-weekly]
verify_jwt = false

[functions.run-connector]
verify_jwt = false

[functions.run-connectors]
verify_jwt = false

[functions.topics]
verify_jwt = false

[functions.send-digest-email]
verify_jwt = false

[functions.trends-api]
verify_jwt = false